version: "3"
abracadabra: lol
services:
  docusaurus:
    build: .
    ports:
      - 1111:1111
      - 35729:35729
      - 99999:99999
    volumes:
      - ./website/sidebars.json:/app/website/sidebars.json
      - ./website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
